### ISSUE TITLE
logsed problem

### ISSUE THREAD

**Issue by Jiacheng188** [Kiris-tingna/log-mining#1]
您好，最近在读logsed的论文时对于过滤operational log的第二步基于编辑距离的聚类方法不是很懂，您知道他是怎么做的吗？

**Comment by Kiris-tingna** [comment]
抱歉  这个很长时间没弄了  不好意思了
> 您好，最近在读logsed的论文时对于过滤operational log的第二步基于编辑距离的聚类方法不是很懂，您知道他是怎么做的吗？
